# Generated by Django 5.1.5 on 2026-02-13 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(help_text="Original text stored in memory")),
                (
                    "vector_id",
                    models.CharField(help_text="ID in vector database", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_input", models.TextField(help_text="User's task or goal")),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="Task status: pending, completed",
                        max_length=50,
                    ),
                ),
                (
                    "final_output",
                    models.TextField(
                        blank=True, help_text="Final AI output", null=True
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Optional confidence score from evaluator",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        help_text="Planner / Worker / Evaluator", max_length=100
                    ),
                ),
                ("input_data", models.TextField(help_text="Input given to this agent")),
                (
                    "output_data",
                    models.TextField(help_text="Output returned by this agent"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="agents.task",
                    ),
                ),
            ],
        ),
    ]
